version: "3.9"

services:
  backend:
    build:
      context: ./backend
      args:
        - DEV=true
    ports:
      - 9000:9000
    volumes:
      - ./backend:/backend
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py wait_for_db &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:9000"
    environment:
      - DB_HOST=db
      - DB_NAME=dbname
      - DB_USER=user
      - DB_PASSWORD=password
      - DEBUG=1
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  dev-postgres-data:
  dev-static-data:
