version: "3.9"

services:
  backend:
    build:
      context: ./backend
    restart: always
    hostname: backend
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    hostname: frontend
    volumes:
      - frontend:/frontend
    depends_on:
      - backend

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - frontend
    ports:
     - 80:8000
    volumes:
      - static-data:/vol/static

volumes:
  postgres-data:
  static-data:
  frontend:
