name: ci

on:
  pull_request_review:
    types: [submitted]
  push:
    branches:
      - main

jobs:
  test-lint:
    if: ${{ (github.event.review.state == 'approved') || (github.ref == 'refs/heads/main')}}
    name: Test and lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
      - name: Lint Code
        run: docker-compose run --rm app sh -c "flake8"
